// <auto-generated />
using System;
using InnAi.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InnAi.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240101225512_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InnAi.Server.Data.Entities.AiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Default")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfInnLevels")
                        .HasColumnType("integer");

                    b.Property<int>("PrecipitationMapSize")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("AiModels");
                });

            modelBuilder.Entity("InnAi.Server.Data.Entities.AiModelResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AiModelId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageDeviation")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("PercentageDeviation")
                        .HasColumnType("double precision");

                    b.Property<string>("PredictionValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiModelId");

                    b.HasIndex("DateTime", "AiModelId")
                        .IsUnique();

                    b.ToTable("AiModelResults");
                });

            modelBuilder.Entity("InnAi.Server.Data.Entities.AiModelResult", b =>
                {
                    b.HasOne("InnAi.Server.Data.Entities.AiModel", "AiModel")
                        .WithMany("Results")
                        .HasForeignKey("AiModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModel");
                });

            modelBuilder.Entity("InnAi.Server.Data.Entities.AiModel", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
